fabtests: Add benchmark option for `FI_OPT_MAX_MSG_SIZE`
ofiwg/libfabric pull request #10147
Opened 2024-07-03 02:14 UTC by darrylabbate

This adds an option (`-X`) for benchmark tests; corresponding to the endpoint options `FI_OPT_MAX_MSG_SIZE`. `fi_setopt()` is called during EP enable with the value requested by the user.

This also includes a few related minor changes to the EFA provider.

2024-07-03 15:40 UTC, shijin-aws requested changes

2024-07-03 15:40 UTC, shijin-aws commented on fabtests/benchmarks/benchmark_shared.c
> +	FT_PRINT_OPTS_USAGE("-X", "maximum untagged message size");
I think using a general `-X` only for untagged message size is not desired. We can introduce a long option `--max-msg-size` for it.

2024-07-03 15:40 UTC, shijin-aws commented on fabtests/common/shared.c
> +		if (ret) {
What will happen if provider doesn't support such option? We should ignore such ENOSUPPORT error

2024-07-03 15:41 UTC, shijin-aws commented
Do you need another commit to add such test to pytest?

2024-07-03 21:21 UTC, darrylabbate commented
> Do you need another commit to add such test to pytest?

Are you asking for a default pytest? I figure we can have a follow-up PR for some kind of EFA zero-copy fabtest.

2024-07-03 21:24 UTC, shijin-aws commented
> Are you asking for a default pytest? I figure we can have a follow-up PR for some kind of EFA zero-copy fabtest.

I prefer to just have it in this PR so we can make it tested by AWS CI. It should be a straightforward incremental change, like what we have in `test_rdm.py`

2024-07-03 22:28 UTC, shijin-aws commented on fabtests/common/shared.c
> +		if (ret && ret != -FI_ENOPROTOOPT) {
I think it's a bug in the man page. In this case we should return `-FI_EOPNOTSUPP`

2024-07-03 22:31 UTC, shijin-aws commented on fabtests/common/shared.c
> +		if (ret && ret != -FI_ENOPROTOOPT) {
Nvm, I think FI_ENOPROTOOPT is OK and that's what efa and shm returns today

2024-07-09 19:51 UTC, shijin-aws commented on fabtests/pytest/efa/test_rdm.py
> +@pytest.mark.functional
can you add rdm_bw as well?

2024-07-09 20:30 UTC, shijin-aws approved these changes

2024-07-09 20:30 UTC, shijin-aws commented
@j-xiong can you review https://github.com/ofiwg/libfabric/pull/10147/commits/fa178bb1fe878de3be948304e3504a9b8da92ef8

2024-07-09 20:53 UTC, j-xiong approved these changes

2024-07-10 06:06 UTC, shijin-aws commented on fabtests/pytest/efa/test_rdm.py
> +def test_rdm_bw_zcpy_recv(cmdline_args, memory_type, message_size):
The `message_size` fixture will have msg size larger than 8192, you need to customize it to make it smaller than 8192

2024-07-10 18:24 UTC, closed without merging

2024-07-10 18:24 UTC, shijin-aws commented
I opened a new PR that reworked the last commit of this PR https://github.com/ofiwg/libfabric/pull/10168