xpmem: Change the log level to info
ofiwg/libfabric pull request #10465
Opened 2024-10-16 23:22 UTC by jiaxiyan

FI_WARN in xpmem introduces too much noise in the log. Change it to FI_INFO.

2024-10-16 23:46 UTC, shijin-aws commented
@jiaxiyan can you update your commit msg too?

2024-10-16 23:47 UTC, shijin-aws requested changes

2024-10-16 23:47 UTC, shijin-aws commented on src/xpmem.c
> +		FI_INFO(&core_prov, FI_LOG_CORE,
I think we only want to make this as INFO, the other places should still be warning as they are unexpected error in libfabric and nothing to do with the kernel module loading

2024-10-16 23:59 UTC, aingerson approved these changes

2024-10-17 02:32 UTC, shijin-aws approved these changes

2024-10-17 02:33 UTC, shijin-aws commented
bot:aws:retest

2024-10-17 17:00 UTC, shijin-aws commented
is Intel CI related (unlikely) ?

2024-10-18 16:56 UTC, shijin-aws commented
@aingerson ^^

2024-10-18 16:58 UTC, j-xiong commented
psm3 failed two newly added atomic tests with the debug build:
```
         fi_rdm_atomic -o all -I 1000 -v -p "psm3"                            : Fail
        fi_rdm_atomic -o all -I 1000 -U -v -p "psm3"                         : Fail
```

They are unrelated to this PR.

2024-10-18 16:59 UTC, merged

2024-10-18 17:01 UTC, aingerson commented
@shijin-aws Yeah sorry that was my fault. Went unnoticed because we have been changing our CI infrastructure a lot lately and it didn't get reported properly. I know the issue and I have a PR to fix it (#10470) but Windows isn't happy with it. I'm going to try to fix it and if I can't by the end of the day, I will disable the test.