prov/shm: remove unnecessary duplicate call to ofi_hmem_init
ofiwg/libfabric pull request #6281
Opened 2020-09-28 20:59 UTC by aingerson

ofi_hmem_init is already called by the core code and does not
need to be called in the shm provider

Signed-off-by: aingerson <alexia.ingerson@intel.com>

2020-09-28 21:40 UTC, shefty approved these changes

2020-09-28 23:47 UTC, shefty requested changes
Need to update for DL build

2020-09-29 02:07 UTC, aingerson commented
@shefty Updated both PRs

2020-09-29 17:33 UTC, shefty commented
bot:aws:retest

2020-09-30 00:03 UTC, merged