prov/efa: Minor cleanups
ofiwg/libfabric pull request #6334
Opened 2020-10-08 22:26 UTC by wckzhang

Minor cleanups patch.

2020-10-08 22:32 UTC, bwbarrett requested changes

2020-10-08 22:32 UTC, bwbarrett commented on prov/efa/src/efa.h
> +/*
using the format that the team has been using already...

2020-10-08 22:32 UTC, bwbarrett commented on prov/efa/src/efa_domain.c
> +		} else {
This is not what I meant.  I meant that the common case end of function should be obvious before you get into cleanup.  There's no need to jump into disable_caches if we never allocated a cache.  So make that an error state, and return 0 right before that.  THen remove the return 0 in line 327.

2020-10-08 23:29 UTC, bwbarrett approved these changes

2020-10-21 14:25 UTC, wckzhang commented
aws:bot:retest

2020-11-10 22:56 UTC, shefty commented
Is the world happy with this PR?

2020-11-11 16:40 UTC, rwespetal commented
aws:bot:retest

2020-11-11 16:41 UTC, rwespetal approved these changes

2020-11-11 19:30 UTC, rwespetal commented
aws:bot:retest

2020-11-12 19:55 UTC, merged