prov/psm3: Moved generation of psm3_revision.c to psm3 only target
ofiwg/libfabric pull request #6621
Opened 2021-03-10 17:49 UTC by acgoldma

Udpated configure to generate psm3_revision.ci, a intermediate file,
from psm3_revision.c.in. Then make uses a psm3_revision.c target that
depends on the intermediate file, psm3_revision.ci, to generate the
checksum and timestamp.

Moved timestamp to only update if checksum does.

Signed-off-by: Goldman, Adam <adam.goldman@intel.com>

2021-03-10 17:53 UTC, acgoldma commented on prov/psm3/Makefile.include
> +prov/psm3/src/psm3_revision.c: prov/psm3/src/psm3_revision.ci
need to add new file to gitignore.

2021-03-10 17:55 UTC, jsquyres commented
I just replied on the other PR -- why not do this inside `configure` and just `AC_DEFINE` the results?

2021-03-10 17:59 UTC, acgoldma commented
> I just replied on the other PR -- why not do this inside `configure` and just `AC_DEFINE` the results?

I am not sure how to handle if someone makes a change to the source file and recompiles without rerunning configure.

2021-03-10 18:33 UTC, jsquyres commented
Do you anticipate that happening in actual customer deployments?

What is the purpose of the checksum, anyway?  And why should it be PSM3-specific?

2021-03-10 18:45 UTC, acgoldma commented
> Do you anticipate that happening in actual customer deployments?

Yes, in the past we have had customers who like to rebuild source and sometimes they make changes for whatever reason.

> What is the purpose of the checksum, anyway? 

It is another method to id the code and identify if a user made 'unsupported' changes to the source tree. 

>And why should it be PSM3-specific?

If you wish to expand this mechanism to other providers/core code, you are welcome to suggest that. PSM3 is will display this ID at runtime if you provide the correct PSM3 ENV.

2021-03-10 19:15 UTC, jsquyres commented
> > What is the purpose of the checksum, anyway?
> 
> It is another method to id the code and identify if a user made 'unsupported' changes to the source tree.

It is not a reliable mechanism; it can easily be broken or defeated.  Case in point: your current implementation will generate the checksome once, even if the code changes, thereby defeating the point of having it.

2021-03-10 20:42 UTC, jsquyres commented
I should clarify.

I realize that we vendors are in an odd position: distributing source code that customers compile and install themselves definitely does lead to support challenges (e.g., customers modifying the code themselves and then calling us for support when it doesn't work).  Having a checksum mechanism is far from perfect (because a "too smart" customer can easily defeat it), but it's a quick-but-weak indicator that the customer is not running the supported version of libfabric.  

If there is a desire to have such a mechanism (with its understood mechanisms), my $0.02 is that it should be at the libfabric level -- not an individual provider.  E.g., a checksum could be an attribute on the provider struct, or somesuch (that would be able to handle in- vs. out-of-tree builds).

Similar for a build timestamp: my $0.02 is that that should be at a libfabric level, not an individual provider.

Yes, libfabric philosophically allows providers to do whatever the heck they want.  But another philosophical tenent is that common stuff that can benefit everyone should be in the core.  And for things like examining (weak) versioning and/or timestamps, it would be better if all vendors/customers could uniformly look for that metadata.

2021-03-11 16:43 UTC, jsquyres requested changes
The latest commit made the mechanism even more convoluted.

1. Is there a reason the timestamp of the compiled library is not sufficient?
2. If the checksum mechanism is going to be used, it needs to be upleveled to the core and use the mechanisms that `make` and the GNU Autotools provide rather than trying to re-invent the wheel.

2021-03-12 15:16 UTC, acgoldma commented
From @ToddRimmer:
> This has the purpose as you described, assuming most folks build the whole thing once (typically using a src.rpm) this helps identify customer modified code or other odd ways they may get things.  The checksum (and other indicators) can be output at runtime for any or all ranks so inconsistent environments can also be identified.  There have been multiple times in the past where a customer reported issues but was not running the version they claimed to be running or had failed to put the same version on all the nodes they meant to.
> 
> The provider can be built in-tree or out-of-tree and integrated directly into a libfabric.so or as a standalone libpsm3-fi.so placed in /usr/src/libfabric (or wherever FI_PROVIDER_PATH points).  When out of tree, the provider itself can be installed and will run against current and older versions of libfabric, such as those in RHEL 7, RHEL 8, etc.  In that environment, a provider specific checksum is needed as the one in libfabric itself doesn't tell us anything about the specific provider version being used.
> 
> Some applications and middleware actually include libfabric.so itself in their packaging, so the standalone mechanisms also permit updated psm3 providers to be used even if the app/middleware version pre-dated psm3's existence or included an outdated version.  We have already validated the psm3 provider (using the libpsm3-fi.so standalone) against a variety of previous libfabric versions, including some included in closed source apps/middlewares.
> 
> This is not intended as a security mechanism and a customer who choses to hack the checksum is just making their own support more difficult.  It sometimes helps developers too as developers may cycle builds quickly and make mistakes, this helps catch such mistakes before running down a deep rathole debugging the wrong code (been there done that :-) )

2021-03-12 15:58 UTC, jsquyres commented
@acgoldma @ToddRimmer I'm not disagreeing; the checksum functionality is somewhat useful.  I said as much in prior replies.

My objections still remain:

1. The latest commit made the mechanism even more convoluted.
2. If the checksum mechanism is going to be used, it needs to be upleveled to the core and use the mechanisms that make and the GNU Autotools provide rather than trying to re-invent the wheel.

Of course this would be a new core functionality and wouldn't apply to older versions of libfabric.  But that doesn't mean the functionality shouldn't be upleveled to Libfabric core.  If you're going to back-port PSM3 to prior versions of libfabric, this would be among the set of differences that would need to be included in the back port.

Additionally, if you're going to do the checksum computation at build time (vs. `configure` time), then do it properly.  Don't give a false sense of functionality by having it only compute the checksum for the *first* build.  That's a clear mis-use of `Make` rules; that's a _bug_.

2021-03-12 17:14 UTC, ToddRimmer commented
> If you're going to back-port PSM3 to prior versions of libfabric, 
Just to be clear, the current version of libfabric and current source tree can be built into libfabric.so or as a standalone OOT libpsm3-fi.so.   We have confirmed the OOT libpsm3-fi.so can simply be placed in /usr/lib64/libfabric and will work against a wide range of libfabric revs, including in-distro revs going back to RHEL 7 and SLES 15 and included inside some middlewares are apps.  This is due to the great work by the libfabric community to maintain ABIs as well as some careful work in PSM3.

We can explore ways to simplify the makefiles, but the current implementation meets all the requirements we had.   configure; make; edit, make  is not a sequence we were concerned about.  Most users, including many of our own internal development scripts, simply run configure every time and most end users simply pull down a source and build it once.  Many users use src.rpm's in which case build it once is the main mechanism.

2021-03-24 14:27 UTC, acgoldma commented
I plan to close this and open a new single PR for further fixes.

2021-03-24 14:27 UTC, closed without merging