efa: Correctly parse environment variables RDMAV_FORK_SAFE and IBV_FORK_SAFE set to 0
ofiwg/libfabric pull request #7430
Opened 2022-02-08 02:29 UTC by nzmsv

Before this change we only checked for existence of these variables in the environment, which made it hard to undo the setting of these variables.

2022-02-08 05:31 UTC, j-xiong commented
Setting the environment variable RDMAV_FORK_SAFE or IBV_FORK_SAFE to any value has the same effect as calling ibv_fork_init(). Value 0 doesn't have any special meaning.

2022-02-08 13:30 UTC, wzamazon commented
@j-xiong  Recently Greg has opened a PR to rdma-core that changed the behavior https://github.com/linux-rdma/rdma-core/pull/1132 to `RDMAV_FORK_SAFE` to 0 means disable fork support.

@nzmsv  Though your patch is merged, it only affects newest version of rdma-core. You current patch can cause silent data corruption when it is with older version of rdma-core:

the workflow is:

1. user set RDMAV_FORK_SAFE to 0
2. EFA provider thinks FORK support is off, thus start using huge pages
3. On older version of rdma-core, fork support is turned on
4. silent data corruption.

Therefore, we cannot accept your patch as is.

Meanwhile, I agree that the current behavior is confusing. I think what we can do is that if user has RDMAV_FORK_SAFE set to 0, EFA exit and print an error message. Ask the user to either upgrade rdma-core or unset the environment variable. But the exit cannot happen in `rxr_init_env`, it need to happen when EFA is actually used, like when creating the domain.

2022-02-08 13:31 UTC, wzamazon requested changes
See my earlier comment

2022-02-12 01:40 UTC, shijin-aws commented
Could you modify the commit/PR title to be `prov/efa: ...` to be consistent with other PRs/commits. This will help us filter commits. Thanks.

2022-03-18 05:47 UTC, closed without merging