prov/util (all) - initial set of patches to allow providers to set lock type
ofiwg/libfabric pull request #7439
Opened 2022-02-12 04:40 UTC by shefty

This series will allow a provider to indicate if a domain should use a mutex or spinlock for its base lock.  So far only the util domain is updated.  Next is to add the CQ, though some preliminary changes are included to make this straightforward.  The shm provider can then be updated to request the use of a spinlock over a mutex to avoid nesting a mutex inside of a spinlock.

Because the code updates the ofi_domain_init() call, most of the providers are touched, but only to pass in a 0 flag to that call.

2022-02-14 23:16 UTC, shefty commented
Updated to set cq lock type based on domain lock type.  Set shm provider to user spinlock.

Error is showing a problem with EFA provider with these updates.  Investigating.

2022-02-15 14:06 UTC, wzamazon commented on prov/util/src/util_cq.c
> +	if (cq->lock_type == OFI_LOCK_MUTEX)
Would it be better to put `lock_type`, `mutex`, `spinlock` into 1 data structure (like `ofi_lock`), and have utility functions liks `ofi_lock_init` and `ofi_lock_destroy`?

2022-02-15 14:21 UTC, wzamazon requested changes
Thank you very much for the PR!

I only have 2 comments:

First is in efa provider, there are two calls to `ofi_mutex_lock/ofi_mutex_unlock`  should be converted to direct calls. IMO.

Second is a suggestion to in implementation, which I believe would make the code cleaner.

2022-02-15 21:45 UTC, aingerson reviewed
Overall looks ok to me though I had the same though as @wzamazon about putting all the lock fields into one common variable and using utility functions. Would we have to update the other util locks as well (util_ep, util_av)? Or is it just the cq because that's the only one that's ever nested?

2022-02-15 22:27 UTC, shefty commented
I'm adding a new lock abstraction to isolate the locking.  The other util classes could be updated, but that's not needed to address the current problem.  The cq and domain locks are being nested inside the shm region lock.

2022-02-15 23:47 UTC, shefty commented
Updated -- added a new locking abstraction: ofi_genlock, which handles the different lock types and callbacks behind a straightforward abstraction.  Providers are updated accordingly.  In general these updates apply:

ofi_mutex_t -> struct ofi_genlock
ofi_mutex_lock -> ofi_genlock_lock()
ofi_mutex_unlock -> ofi_genlock_unlock()

Lock callbacks are removed from the util code.  (I see the build issues that obviously don't occur on my system.  Investigating -- looks like missing includes or problem with static inlines.)

2022-02-15 23:51 UTC, shefty commented
Build issues are related to macro use in free build for spinlock and mutex calls.  sigh...  I'll fix, but the patch concepts will be the same.

2022-02-16 02:05 UTC, wzamazon approved these changes

2022-02-16 02:06 UTC, wzamazon commented
Thank you for the update!

I verified that it fixed the performance issue mentioned in https://github.com/ofiwg/libfabric/issues/7429

2022-02-16 17:51 UTC, merged