print ofi_mr_map_remove return correctly upon failure
ofiwg/libfabric pull request #7884
Opened 2022-07-14 20:16 UTC by ryanamazon

When ofi_mr_map_remove returns a failure return code, that code is not
the one that is included in the debug message.  This makes it so that
the returned code is logged.

Signed-off-by: Ryan Hankins <rqh@amazon.com>

2022-07-14 20:18 UTC, wzamazon approved these changes

2022-07-14 20:18 UTC, wzamazon commented
Thank you!

2022-07-14 21:49 UTC, j-xiong commented
Please add "prov/efa: " prefix to the title of commit message since it's a efa specific fix.

2022-07-14 21:51 UTC, wzamazon requested changes
Please adjust the commit message as @j-xiong suggested

2022-07-15 23:31 UTC, j-xiong approved these changes

2022-07-15 23:31 UTC, merged