contrib/intel: add ability to set specific environment variables per test
ofiwg/libfabric pull request #7935
Opened 2022-08-08 23:44 UTC by aingerson

Allow setting of environment variables per test run. This is specified through the
runtests.py arg --user_env with a string formatted as a dictionary. For example:

runtests.py --prov=shm --test=fabtests --slurm --user_env="{'FI_SHM_DISABLE_CMA':1,'FI_LOG_LEVEL'='info'}"

This lets us test certain runtime parameters for certain cases only.

This also removes the hard coded verbs variables because FI_VERBS_MR_CACHE_ENABLE was deprecated and
FI_VERBS_INLINE_SIZE is already defaulted to 256 bytes so setting it is redundant.

Signed-off-by: Alexia Ingerson <alexia.ingerson@intel.com>

2022-08-08 23:45 UTC, aingerson commented
@zachdworkin

2022-08-09 13:44 UTC, zachdworkin commented
@aingerson I am replaying this for you with changes to the Jenkinsfile so that it picks-up your contrib/intel/jenkins changes.

2022-08-11 15:45 UTC, zachdworkin requested changes

2022-08-11 15:45 UTC, zachdworkin commented on contrib/intel/jenkins/Jenkinsfile
> +                    python3.7 ${env.WORKSPACE}/contrib/intel/jenkins/build.py --build_item=builddir
All of these need to leave the "/py_scripts" in when you merge.

2022-08-11 15:45 UTC, zachdworkin commented on contrib/intel/jenkins/Jenkinsfile
> +                stage('dsa') {
This one will also need the /py_scripts redirection for security before merging

2022-08-11 15:45 UTC, zachdworkin commented on contrib/intel/jenkins/build.py
> +def build_fabtests(libfab_install_path, mode, dsa):
Do you need dsa for fabtests configure/make? I thought it was just for libfabric

2022-08-11 15:45 UTC, zachdworkin commented on contrib/intel/jenkins/Jenkinsfile
> +                    agent {node {label 'cst-pvc'}}
Is the tests.py file changes missing from this? It looks like the --user_env option doesn't get used?

2022-08-11 16:46 UTC, aingerson commented
@zachdworkin Sorry I thought this got merged and repushed other things to this branch 🤦

2022-08-11 16:55 UTC, aingerson commented
@zachdworkin Ok sorry about that. Should be back to normal now!

2022-08-15 17:46 UTC, merged