Daos summary
ofiwg/libfabric pull request #8117
Opened 2022-10-14 21:25 UTC by nikhilnanal

2022-12-02 22:25 UTC, zachdworkin requested changes
Looks good, some minor nitpicks and one change necessary

2022-12-02 22:34 UTC, nikhilnanal commented on contrib/intel/jenkins/summary.py
> +class DaosSummarizer(Summarizer):
there was one line which was exceeding. fixed that.

2022-12-02 22:34 UTC, nikhilnanal commented on contrib/intel/jenkins/summary.py
> -                         'oneccl', 'shmem', 'ze', 'multinode', 'all'])
added

2022-12-02 22:40 UTC, nikhilnanal commented on contrib/intel/jenkins/summary.py
> -                         'oneccl', 'shmem', 'ze', 'multinode', 'all'])
added

2022-12-02 22:40 UTC, nikhilnanal commented on contrib/intel/jenkins/Jenkinsfile
> +              python3.7 ${env.WORKSPACE}/${SCRIPT_LOCATION}/summary.py -v --summary_item=daos
put it in the success stage for daos.

2022-12-03 00:28 UTC, zachdworkin approved these changes
Summary in jenkins report looks good!

2022-12-05 18:46 UTC, zachdworkin requested changes
Can you change your commit messages from "Intel CI:" -> "contrib/intel/jenkins:" to be consistent?

There is also one typo that needs to be fixed before we can merge this.

2022-12-05 18:46 UTC, zachdworkin commented on contrib/intel/jenkins/summary.py
> +                         'oneccl', 'shmem', 'ze', 'mutlinode', 'daos', 'all'])
multinode is misspelled

2022-12-05 23:56 UTC, nikhilnanal commented on contrib/intel/jenkins/summary.py
> +                         'oneccl', 'shmem', 'ze', 'mutlinode', 'daos', 'all'])
corrected!

2022-12-06 00:29 UTC, zachdworkin approved these changes

2022-12-06 18:04 UTC, merged