prov/efa: Remove HMEM check from rxr_ep_ctrl()
ofiwg/libfabric pull request #8337
Opened 2022-12-09 21:21 UTC by darrylabbate

This check had essentially no effect

Signed-off-by: Darryl Abbate <drl@amazon.com>

2022-12-13 17:15 UTC, sunkuamzn approved these changes

2022-12-15 02:26 UTC, wzamazon requested changes
Can you add some detail in the commit message regarding why the check has no effect?

2022-12-15 19:43 UTC, wzamazon approved these changes
It would be better to add that

```
the function check whether efa_domain->util_domain.info_domain_caps has FI_HMEM", but FI_HMEM is not a domain capability according to document to fi_domain
```

2022-12-16 01:41 UTC, darrylabbate commented
@wzamazon See latest commit message. Good to merge?

2022-12-16 01:42 UTC, merged