[v1.17.x] prov/efa: fix double free in rxr endpoint init
ofiwg/libfabric pull request #8523
Opened 2023-02-16 20:23 UTC by wenduwan

Manually apply a patch to prevent rdm_info from being freed twice. Cherry-picking the fix on main branch results in conflict, and thus we do a simpler fix instead.

2023-02-16 20:25 UTC, wzamazon approved these changes

2023-02-16 20:27 UTC, lrbison approved these changes
lgtm

2023-02-16 20:37 UTC, qkoziol requested changes
Although this is technically correct today, it would be better if the rdm_info variable was initialized to NULL when it was declared.  That way if the code is restructured and the goto operations are changed, the code will be safer.   (Probably should set rxp_ep to NULL also, and protect freeing it also)

2023-02-16 21:08 UTC, wenduwan commented
> 

Thank you. The suggestion makes sense to me. Updated commit accordingly.

2023-02-16 21:09 UTC, qkoziol approved these changes
Thanks for updating!

2023-02-16 21:09 UTC, lrbison approved these changes

2023-02-17 14:40 UTC, wzamazon approved these changes

2023-02-17 14:41 UTC, merged