prov/efa: Check FI_EFA_USE_DEVICE_RDMA per domain
ofiwg/libfabric pull request #8524
Opened 2023-02-16 20:48 UTC by vidsouza

Prior to this change FI_EFA_USE_DEVICE_RDMA was checked only once when the provider is initialized. Due to this different plugins/libraries setting up the environment for various applications cannot modify the value of this environment variable.

This patch provides this possibility by checking the value of FI_EFA_USE_DEVICE_RDMA once per domain.

2023-02-16 23:29 UTC, darrylabbate commented on prov/efa/src/rdm/rxr_env.c
> +			" FI_EFA_USE_DEVICE_RDMA is boolean and can be set to only 0 or 1. \n");
Same comment I left in #8529 applies here

2023-02-17 00:19 UTC, qkoziol approved these changes

2023-02-17 14:53 UTC, wzamazon requested changes
Thanks! Looks good to me. 

My major concern is the usage of a global variable.

Have a few comments regarding comments etc.

2023-02-17 14:53 UTC, wzamazon commented on prov/efa/src/efa_domain.c
> +	// Check the value of environment variable FI_EFA_USE_DEVICE_RDMA
Use `/* */` style comment for C.

2023-02-17 14:53 UTC, wzamazon commented on prov/efa/src/rdm/rxr_env.c
> + * can be set or not. */
We use doxygen style comment for function header.

Example: https://github.com/ofiwg/libfabric/blob/c1f7b8b6e4d7ad25c3f6e38ca49b276ed309ef00/prov/efa/src/rdm/rxr_op_entry.c#L356

2023-02-17 14:53 UTC, wzamazon commented on prov/efa/src/rdm/rxr_env.c
> +	rxr_env_define_use_device_rdma();
call this function inside `rxr_env_define`.

2023-02-17 14:53 UTC, wzamazon commented on prov/efa/src/rdm/rxr_env.c
> +	// Specify the help info about the usage of RDMA in this device.
Use `/* */` for C.

2023-02-17 14:53 UTC, wzamazon commented on prov/efa/src/rdm/rxr_env.c
> +static int use_device_rdma;
No. Do not use a global variable.

2023-02-17 14:53 UTC, wzamazon commented on prov/efa/src/rdm/rxr_env.c
> +			use_device_rdma = 0;
Do not use global variable. Get the default value from `g_device_list[0].ibv_attr.vendor_part_id` in `rxr_env_get_use_device_rdma`.

2023-02-17 14:53 UTC, wzamazon commented on prov/efa/src/rdm/rxr_env.c
> +	ret = fi_param_get_bool(&efa_prov, "use_device_rdma", &use_device_rdma);
Do not use global variable

2023-02-18 05:05 UTC, merged