fabtests/examples: Add libfabric examples
ofiwg/libfabric pull request #8736
Opened 2023-03-30 22:51 UTC by Juee14Desai

Add examples to explain basic libfabric apis. Four examples are added:

example_rdm.c:
Explain simple message exchange between server and client using RDM endpoint.

example_rdm_oob.c:
This example explains simple meesage exchange with out of band addressing capability.

example_rdm_rma.c:
Explain message exchange using remote memory access. Two operations are explained
here, remote write and remote read. In local write operation, client is going to write data
from its local write buffer to the servers write buffer. In remote read operation, the server
is going to read data from client’s read buffer into its own local read buffer.

example_rdm_tagged.c:
This example demonstrates how tagged messages work and specifically how the messages
are received in the same order as they were sent.

2023-03-30 23:39 UTC, Juee14Desai commented
Hi @shefty,

Please review these examples. I am quite late for the PR but I think these are in much better shape than when I presented. I am not able to request review from you so tagging you here.

Thanks,
Juee

2023-03-30 23:42 UTC, shefty requested changes
See comments on example_rdm.c only.  Other tests were not reviewed.

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> +	hints->tx_attr->op_flags = FI_DELIVERY_COMPLETE;
I would move the initialization of hints into a function that is placed above 'initialization'.  This is the first step that an app needs to take.

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> +	 * The first OFI call to happen for initialization is fi_getinfo which
The first call is usually fi_allocinfo() for the hints.  See comment below about moving hints initialization above this function.

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> +	 */
I'd remove all comments that simply list the call like this.  The call itself should be sufficient.

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> +	 */
drop comment

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> +	 */
drop comment

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> +	 * hardware.
Stop comment at Different providers support different types of endpoints.  The rest of the comment is no longer valid.

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> +	 */
drop comment

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> +	 */
drop comment

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> +	 * thse addresses to indexed addresses, starting with fi_addr 0. These
thse -> these

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> +	 * traditional TCP listen/connect/accept steps.
remove 'TCP' from comment

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> +/* All OFI resources are cleaned up using the same fi_close(fid) call. */
Expand comment to indicate that resources must be closed in a specific order to allow references between objects to be removed correctly.  E.g. the EP must be closed before the CQ or AV.

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> +	/* fi_close(struct fid *ep); */
remove comments like these -- they end up being more distracting than helpful.

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> + * Initializes all basic OFI resources to allow for a server/client to
Replace 'OFI' with 'libfabric everywhere.

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> +fi_addr_t fi_addr = FI_ADDR_UNSPEC;
The above can be declared as static.

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> +	char *msg = "Hello, server! I am the client you've been waiting for!\0";
\0 at end of string is not needed.

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> +	(void) snprintf(buf, BUF_SIZE, "%s", msg);
There's not really a reason to copy a string to another buffer just to send the data.  Just pass msg into fi_send().

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> +		ret = fi_send(ep, buf, BUF_SIZE, NULL, fi_addr, NULL);
Note that this assumes an inject size >= sizeof(msg), or that memory registration isn't needed.  That should be captured in the hints (if assuming inject_size), or a comment (if we're not supporting memory registration).

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> + * message. Similar to the receive buffer posting porcess, when posting a send
porcess -> process

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> +static int wait_cq(void)
rename to spin_for_comp()

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> +//Set anything in hints that the application needs
outdented comments should be removed or indented.  There's also a mix of comment format.

2023-03-30 23:42 UTC, shefty commented on fabtests/examples/example_rdm.c
> +
I would add setting hints->mode = 0 and hints->domain_attr->mr_mode = 0, with comments explaining what the modes do

2023-04-07 04:19 UTC, Juee14Desai commented
Only changed example_rdm.c, others are pending.

2023-04-07 05:20 UTC, Juee14Desai commented
All the examples are updated according to feedback received on example_rdm.c.

2023-07-14 22:04 UTC, zachdworkin commented
@Juee14Desai You need to rebase to pickup the cloudbees CI files

2024-01-04 10:35 UTC, closed without merging