include/rdma: improve API
ofiwg/libfabric pull request #8747
Opened 2023-04-01 16:56 UTC by aingerson

2023-04-02 04:45 UTC, shefty commented
This. Is. Beautiful.  Now, where's that dancing monkey?

2023-04-02 04:55 UTC, shefty requested changes

2023-04-02 04:55 UTC, shefty commented on include/rdma/fi_atomic.h
> +	size_t			iovcount;
C should be upper case.

2023-04-02 04:55 UTC, shefty commented on include/rdma/fi_atomic.h
> +fiAtomicvalid(struct fid_ep *ep,
V should be upper case.  Comment applies to other calls.

2023-04-02 04:55 UTC, shefty commented on include/rdma/fi_atomic.h
> +fiCompareAtomicmsg(struct fid_ep *ep,
M in Msg should be upper case.  Comment applies elsewhere.

2023-04-03 15:47 UTC, closed without merging

2023-04-03 16:12 UTC, j-xiong commented
Good one!