[Intel/CI]: enable fabtests for ucx
ofiwg/libfabric pull request #9049
Opened 2023-06-15 23:52 UTC by nikhilnanal

2023-06-16 17:13 UTC, zachdworkin requested changes
mostly looks good, can you also add the ucx provider to the summary.py file? I think its not getting picked up for the summarizer.

2023-06-16 17:13 UTC, zachdworkin commented on contrib/intel/jenkins/Jenkinsfile
> +                run_fabtests("ucx", "totodile", "2", "ucx")
can we also use squirtle here or no?

2023-06-16 17:13 UTC, zachdworkin commented on contrib/intel/jenkins/build.py
> +    parser.add_argument('--ucx', help="build with ucx", default=False, action='store_true')
line length

2023-06-16 17:33 UTC, aingerson reviewed
The commits feel out of order. The second one which adds a special ucx build is after the one that adds the testing and modifies things the first one changed. 
I also don't really understand the need for the second commit in general (the separate build)

2023-06-16 17:33 UTC, aingerson commented on fabtests/test_configs/ucx/ucx.exclude
> +#
Extra # here

2023-06-16 17:33 UTC, aingerson commented on fabtests/test_configs/ucx/ucx.exclude
>  rdm g00n13s
Since the negative test is already excluded here, we shouldn't need the -N argument in the CI run

2023-06-20 23:30 UTC, merged

2023-06-20 23:33 UTC, aingerson commented
@nikhilnanal I know this just got merged, but could you explain the need for the separate ucx build? I didn't understand why it was added or how it works.

2023-06-20 23:40 UTC, shefty commented
Isn't that just checking if ucx libraries are present and enabling the provider in the build if so?

2023-06-20 23:46 UTC, aingerson commented
It didn't look like that to me? It seemed like it was iterating through all the nodes and installing libfabric again on all the nodes with ucx? We already have provider lists for every cluster that specifies which providers to specifically enable on the config line:
```
    if (cluster == 'daos'):
        prov_list = common.daos_prov_list
    elif (cluster == 'dsa'):
        prov_list = common.dsa_prov_list
    else:
        prov_list = common.default_prov_list

    for prov in prov_list:
       config_cmd.append(f'--enable-{prov}={enable_prov_val}')
```

2023-06-21 00:12 UTC, nikhilnanal commented
> @nikhilnanal I know this just got merged, but could you explain the need for the separate ucx build? I didn't understand why it was added or how it works.

CVLs and mlx conflict on mofed(contains libuc*) installation. test binaries complain of missing libuc* dependencies on cvls and nodes which dont have mofed installed. To make that work on cvl we have a build without ucx enabled which does not  need those dependencies.

2023-06-21 16:30 UTC, nikhilnanal commented
> It didn't look like that to me? It seemed like it was iterating through all the nodes and installing libfabric again on all the nodes with ucx? We already have provider lists for every cluster that specifies which providers to specifically enable on the config line:
> 
> ```
>     if (cluster == 'daos'):
>         prov_list = common.daos_prov_list
>     elif (cluster == 'dsa'):
>         prov_list = common.dsa_prov_list
>     else:
>         prov_list = common.default_prov_list
> 
>     for prov in prov_list:
>        config_cmd.append(f'--enable-{prov}={enable_prov_val}')
> ```

it doesnt iterate through all the nodes. It  builds a separate libfabric with enable-ucx.  The Jenkins ucx nodes uses this build while other nodes use the the non ucx build.