prov/sm2: proto-based progress
ofiwg/libfabric pull request #9055
Opened 2023-06-16 22:03 UTC by lrbison

2023-06-16 22:29 UTC, a-szegel requested changes

2023-06-16 22:29 UTC, a-szegel commented on prov/sm2/src/sm2_progress.c
> -		default:
Why are you getting rid of the default case?

2023-06-16 22:29 UTC, a-szegel commented on prov/sm2/src/sm2_progress.c
> +			ret = sm2_progress_proto_return(ep, xfer_entry);
Can we rename this to be inject return?

2023-06-16 22:29 UTC, a-szegel commented on prov/sm2/src/sm2_progress.c
> +		case (sm2_proto_return):
Case 1: Progress
```
sm2_progress_recv(): Switch 1 PROTO 
sm2_progress_proto_inject(): Switch 2 OP
sm2_start_common(): Switch 3 PROTO     #### BAD, we shouldn't switch twice on the same thing... this needs to go
```

Case 2 posting buffers:
```
sm2_start_common(): Switch 1 PROTO  # this switch needs to happen on unexpected msg path
```

I think part of this change needs to get rid of sm2_start_common() b/c now those paths are diverging.

2023-06-20 16:54 UTC, lrbison commented
Closing this for now.  It might be back with major changes.

2023-06-20 16:54 UTC, closed without merging