prov/mrail: Turn Noisy WARN to INFO
ofiwg/libfabric pull request #9131
Opened 2023-07-10 17:14 UTC by a-szegel

Currently, "OFI_MRAIL_ADDR_STRC env variable not set!" gets logged at warning on every run, even if we aren't using the mrail provider. Change this to be an info to clean up the warning log.

2023-07-10 17:23 UTC, wzamazon approved these changes

2023-07-10 17:30 UTC, shefty requested changes
please remove level stack variable, which is no longer used

2023-07-10 20:58 UTC, aingerson approved these changes

2023-07-12 21:28 UTC, a-szegel commented
@shefty Are you good with this?

2023-07-12 21:29 UTC, a-szegel commented
bot:aws:retest

2023-07-13 02:47 UTC, merged