prov/shm, fabtests/hmem, contrib/intel: enable full fabtests FI_HMEM support and enable in Intel CI
ofiwg/libfabric pull request #9404
Opened 2023-10-05 01:26 UTC by aingerson

Full patch set enables shm+FI_HMEM to be run with complete fabtests set (by fixing missing support and adding missing shm functionality) and enables full runs on the Intel CI

- Fix missing fabtests support for FI_HMEM (fi_rdm, fi_rdm_event)
- Add support for use of FI_ATOMIC with FI_HMEM
- Remove ZE-specific stage class since we can run directly through fabtests script
- Fix ZE bug using incorrect device id
- Remove ZE v2 testing (fully replace with v3)

2023-10-05 01:27 UTC, aingerson commented
I know it's touching a lot of different areas of the code. I can split it up into different PRs if you like but want to make sure all of them together pass everything

2023-10-05 13:11 UTC, zachdworkin requested changes

2023-10-05 13:11 UTC, zachdworkin commented on contrib/intel/jenkins/Jenkinsfile
This commit should probably also include removing the ze-shm v2 block from the summary.py file. Should be ~lines 878-887 in summary.py

2023-10-05 14:37 UTC, aingerson commented on contrib/intel/jenkins/Jenkinsfile
Updated

2023-10-05 14:38 UTC, zachdworkin approved these changes

2023-10-05 21:26 UTC, zachdworkin requested changes

2023-10-05 21:26 UTC, zachdworkin commented on contrib/intel/jenkins/Jenkinsfile
> +  if (way)
this needs curly brackets around it. Right now youre forcing fabtests to only do reg since the modes = ["reg"] line is not protected in this if.

2023-10-06 16:08 UTC, zachdworkin approved these changes

2023-10-06 16:16 UTC, aingerson commented
bot:aws:retest

2023-10-06 22:17 UTC, shijin-aws commented
It fails AWS CI in rdm_atomic test on single node 

```
--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

server_command: ssh -n -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o BatchMode=yes 172.31.45.84 'timeout 1800 /bin/bash --login -c '"'"'FI_EFA_USE_DEVICE_RDMA=0 /home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9404-debug/install/fabtests/bin/fi_rdm_atomic -p efa -E=9230'"'"''

client_command: ssh -n -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o BatchMode=yes 172.31.45.84 'timeout 1800 /bin/bash --login -c '"'"'FI_EFA_USE_DEVICE_RDMA=0 /home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9404-debug/install/fabtests/bin/fi_rdm_atomic -p efa -E=9230 172.31.45.84'"'"''
client_stdout:
Provider doesn't support FI_MIN base atomic operation on FI_FLOAT_COMPLEX
Provider doesn't support FI_MIN base atomic operation on FI_DOUBLE_COMPLEX
Provider doesn't support FI_MIN base atomic operation on FI_LONG_DOUBLE
Provider doesn't support FI_MIN base atomic operation on FI_LONG_DOUBLE_COMPLEX
Provider doesn't support FI_MIN base atomic operation on FI_INT128
Provider doesn't support FI_MIN base atomic operation on FI_UINT128
Provider doesn't support FI_MAX base atomic operation on FI_FLOAT_COMPLEX
Provider doesn't support FI_MAX base atomic operation on FI_DOUBLE_COMPLEX
Provider doesn't support FI_MAX base atomic operation on FI_LONG_DOUBLE
Provider doesn't support FI_MAX base atomic operation on FI_LONG_DOUBLE_COMPLEX
Provider doesn't support FI_MAX base atomic operation on FI_INT128
Provider doesn't support FI_MAX base atomic operation on FI_UINT128
Provider doesn't support FI_SUM base atomic operation on FI_DOUBLE_COMPLEX
Provider doesn't support FI_SUM base atomic operation on FI_LONG_DOUBLE
Provider doesn't support FI_SUM base atomic operation on FI_LONG_DOUBLE_COMPLEX
Provider doesn't support FI_SUM base atomic operation on FI_INT128
Provider doesn't support FI_SUM base atomic operation on FI_UINT128
name                                              bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
FI_INT8_FI_MIN_base_lat                           1       1k      1000        0.00s      0.57       1.74       0.57
FI_UINT8_FI_MIN_base_lat                          1       1k      1000        0.00s      0.57       1.74       0.57
FI_INT16_FI_MIN_base_lat                          2       1k      1.9k        0.00s      1.18       1.70       0.59
FI_UINT16_FI_MIN_base_lat                         2       1k      1.9k        0.00s      1.18       1.70       0.59
FI_INT32_FI_MIN_base_lat                          4       1k      3.9k        0.00s      2.35       1.70       0.59
FI_UINT32_FI_MIN_base_lat                         4       1k      3.9k        0.00s      2.39       1.67       0.60
FI_INT64_FI_MIN_base_lat                          8       1k      7.8k        0.00s      4.69       1.71       0.59
FI_UINT64_FI_MIN_base_lat                         8       1k      7.8k        0.00s      4.66       1.72       0.58
FI_FLOAT_FI_MIN_base_lat                          4       1k      3.9k        0.00s      2.37       1.69       0.59
FI_DOUBLE_FI_MIN_base_lat                         8       1k      7.8k        0.00s      4.68       1.71       0.58
FI_INT8_FI_MAX_base_lat                           1       1k      1000        0.00s      0.59       1.71       0.59
FI_UINT8_FI_MAX_base_lat                          1       1k      1000        0.00s      0.59       1.70       0.59
FI_INT16_FI_MAX_base_lat                          2       1k      1.9k        0.00s      1.19       1.68       0.60
FI_UINT16_FI_MAX_base_lat                         2       1k      1.9k        0.00s      1.18       1.69       0.59
FI_INT32_FI_MAX_base_lat                          4       1k      3.9k        0.00s      2.36       1.70       0.59
FI_UINT32_FI_MAX_base_lat                         4       1k      3.9k        0.00s      2.37       1.69       0.59
FI_INT64_FI_MAX_base_lat                          8       1k      7.8k        0.00s      4.74       1.69       0.59
FI_UINT64_FI_MAX_base_lat                         8       1k      7.8k        0.00s      4.73       1.69       0.59
FI_FLOAT_FI_MAX_base_lat                          4       1k      3.9k        0.00s      2.43       1.65       0.61
FI_DOUBLE_FI_MAX_base_lat                         8       1k      7.8k        0.00s      4.76       1.68       0.59
FI_INT8_FI_SUM_base_lat                           1       1k      1000        0.00s      0.59       1.70       0.59
FI_UINT8_FI_SUM_base_lat                          1       1k      1000        0.00s      0.59       1.69       0.59
FI_INT16_FI_SUM_base_lat                          2       1k      1.9k        0.00s      1.17       1.71       0.59
FI_UINT16_FI_SUM_base_lat                         2       1k      1.9k        0.00s      1.19       1.68       0.60
FI_INT32_FI_SUM_base_lat                          4       1k      3.9k        0.00s      2.38       1.68       0.59
FI_UINT32_FI_SUM_base_lat                         4       1k      3.9k        0.00s      2.37       1.69       0.59
FI_INT64_FI_SUM_base_lat                          8       1k      7.8k        0.00s      4.75       1.68       0.59
FI_UINT64_FI_SUM_base_lat                         8       1k      7.8k        0.00s      4.78       1.67       0.60
FI_FLOAT_FI_SUM_base_lat                          4       1k      3.9k        0.00s      2.37       1.69       0.59
FI_DOUBLE_FI_SUM_base_lat                         8       1k      7.8k        0.00s      4.73       1.69       0.59
FI_FLOAT_COMPLEX_FI_SUM_base_lat                  8       1k      7.8k        0.00s      4.76       1.68       0.60
FI_INT8_FI_PROD_base_lat                          1       1k      1000        0.00s      0.59       1.69       0.59
FI_UINT8_FI_PROD_base_lat                         1       1k      1000        0.00s      0.59       1.69       0.59
FI_INT16_FI_PROD_base_lat                         2       1k      1.9k        0.00s      1.19       1.69       0.59
FI_UINT16_FI_PROD_base_lat      Provider doesn't support FI_PROD base atomic operation on FI_DOUBLE_COMPLEX
Provider doesn't support FI_PROD base atomic operation on FI_LONG_DOUBLE
Provider doesn't support FI_PROD base atomic operation on FI_LONG_DOUBLE_COMPLEX
Provider doesn't support FI_PROD base atomic operation on FI_INT128
Provider doesn't support FI_PROD base atomic operation on FI_UINT128
Provider doesn't support FI_LOR base atomic operation on FI_DOUBLE_COMPLEX
Provider doesn't support FI_LOR base atomic operation on FI_LONG_DOUBLE
Provider doesn't support FI_LOR base atomic operation on FI_LONG_DOUBLE_COMPLEX
Provider doesn't support FI_LOR base atomic operation on FI_INT128
Provider doesn't support FI_LOR base atomic operation on FI_UINT128
Provider doesn't support FI_LAND base atomic operation on FI_DOUBLE_COMPLEX
Provider doesn't support FI_LAND base atomic operation on FI_LONG_DOUBLE
Provider doesn't support FI_LAND base atomic operation on FI_LONG_DOUBLE_COMPLEX
Provider doesn't support FI_LAND base atomic operation on FI_INT128
Provider doesn't support FI_LAND base atomic operation on FI_UINT128
                  2       1k      1.9k        0.00s      1.20       1.67       0.60
FI_INT32_FI_PROD_base_lat                         4       1k      3.9k        0.00s      2.37       1.69       0.59
FI_UINT32_FI_PROD_base_lat                        4       1k      3.9k        0.00s      2.37       1.69       0.59
FI_INT64_FI_PROD_base_lat                         8       1k      7.8k        0.00s      4.73       1.69       0.59
FI_UINT64_FI_PROD_base_lat                        8       1k      7.8k        0.00s      4.73       1.69       0.59
FI_FLOAT_FI_PROD_base_lat                         4       1k      3.9k        0.00s      2.39       1.67       0.60
FI_DOUBLE_FI_PROD_base_lat                        8       1k      7.8k        0.0 [...]

2023-10-06 22:21 UTC, shijin-aws commented
It also failed the`osu_get_acc_latency` test with Open MPI on 2 node, which I don't understand right now. As it shouldn't use shm in this case

```

INFO     root:utils.py:67 Executing command: export PATH=/opt/amazon/openmpi/bin:$PATH;export LD_LIBRARY_PATH=/home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9404/install/libfabric/lib;/opt/amazon/openmpi/bin/mpirun --wdir . -n 2 --hostfile /home/ec2-user/PortaFiducia/hostfile --map-by ppr:1:node --timeout 1800 -x MPIEXEC_TIMEOUT=1800 -x LD_LIBRARY_PATH=/home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9404/install/libfabric/lib -x PATH  /home/ec2-user/PortaFiducia/build/workloads/omb/openmpi-v4.1.5/source/osu-micro-benchmarks-7.0-lrbison3/c/mpi/one-sided/osu_get_acc_latency   2>&1 | tee /home/ec2-user/PortaFiducia/build/workloads/omb/openmpi-v4.1.5/run/one-sided/osu_get_acc_latency/node2-ppn1.txt
INFO     root:utils.py:466 mpirun output:
# OSU MPI_Get_accumulate latency Test v7.0-lrbison3
# Window creation: MPI_Win_create
# Synchronization: MPI_Win_lock/unlock
# Size          Latency (us)
[ip-172-31-45-84:836217] *** Process received signal ***
[ip-172-31-45-84:836217] Signal: Segmentation fault (11)
[ip-172-31-45-84:836217] Signal code: Address not mapped (1)
[ip-172-31-45-84:836217] Failing at address: 0x3200000049
[ip-172-31-45-84:836217] [ 0] /lib64/libpthread.so.0(+0x12cf0)[0x7fc5d05c9cf0]
[ip-172-31-45-84:836217] [ 1] /home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9404/install/libfabric/lib/libfabric.so.1(+0x1f32c)[0x7fc5c34ce32c]
[ip-172-31-45-84:836217] [ 2] /home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9404/install/libfabric/lib/libfabric.so.1(+0x1f543)[0x7fc5c34ce543]
[ip-172-31-45-84:836217] [ 3] /home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9404/install/libfabric/lib/libfabric.so.1(+0xb04a3)[0x7fc5c355f4a3]
[ip-172-31-45-84:836217] [ 4] /home/ec2-user/PortaFiducia/build/
```

2023-10-12 16:21 UTC, aingerson commented
@shijin-aws @a-szegel Updated PR with fix in efa for passing in the correct shm descriptor into the atomic calls. Let me know if you see any issues with it!

2023-10-13 17:53 UTC, aingerson commented
@a-szegel @shijin-aws The AWS CI was still failing with a similar MR descriptor issue so I added another fix and now it's passing but it's weird that everything else was passing without that and only the atomic path seems to be problematic... Let me know what you think or if you want to rerun/do more testing to investigate the impact before merging.

2023-10-13 18:02 UTC, shijin-aws commented
@aingerson Your fix to efa provider looks reasonable to me, thanks.

> it's weird that everything else was passing without that and only the atomic path seems to be problematic... 
Are you talking about this fix https://github.com/ofiwg/libfabric/pull/9404/commits/61140ecd148f41f5076865d63179da15861729fd?

I think that function assumes shm_desc is only updated when efa_mr is present. We already set shm_desc as NULL before calling this function in `efa_rdm_msg` and `efa_rdm_rma`. Before your change, `efa_rdm_atomic_init_shm_msg` implement this initialization. I think your fix is good for the general usage of this function, thanks!

2023-10-13 18:07 UTC, aingerson commented
@shijin-aws Thank you for the explanation! I missed the NULL initialization in the msg and RMA paths but that makes sense now. Would you like me to remove the other initialization so that you don't have to initialize twice? Or just leave it?

2023-10-13 18:10 UTC, shijin-aws commented
I think removing other initialization is better, thank you

2023-10-13 18:22 UTC, aingerson commented
@shijin-aws Updated to remove the NULL initialization in the other places. It was missing in the readmsg and writemsg paths so could be good to backport the change to make sure. I'll leave that up to you though.

2023-10-13 18:26 UTC, shijin-aws commented
I will backport your fix commits for efa to v1.19.x, thanks

2023-10-13 18:31 UTC, shijin-aws commented
>It was missing in the readmsg and writemsg paths so could be good to backport the change to make sure.

Actually they make the **shm_desc as NULL, so it should be no issue. https://github.com/ofiwg/libfabric/blob/main/prov/efa/src/rdm/efa_rdm_rma.c#L155

2023-10-14 00:23 UTC, aingerson commented
@shijin-aws @a-szegel More failures happened when I removed the NULL initialization, and it was because there were a lot of checks that initialized the shm_desc conditionally so I had to remove them all. I also did a little of cleanup with some initialization that seemed unnecessary to cleanup the shm send path. Let me know if I overstepped and you want me to undo those.

2023-10-14 00:26 UTC, shijin-aws commented
@aingerson could you revert those removal for NULL and leave them there. We will follow up and refactor them carefully. Sorry for your extra work!

2023-10-16 16:57 UTC, a-szegel commented
The AWS failure is not related to this change (TCP).

2023-10-16 16:57 UTC, a-szegel commented
bot:aws:retest

2023-10-16 17:02 UTC, a-szegel approved these changes

2023-10-16 19:59 UTC, merged