prov/tcp: Correct setting of completion flags
ofiwg/libfabric pull request #9460
Opened 2023-10-20 22:00 UTC by nikhilnanal

This PR makes 3 changes:
1. setting of FI_COMPLETION flags for data transfer interfaces(sends and rmas) by combining it with default  settings for the msg flags and op flags
2. Inheriting tx rx flags set during msg endpoint creation from the corresponding rdm endpoint when connection is being created.  For example, if the application requested selective completion then the corresponding msg endpoint is created with the same settings. 
3. re-enables mpichsuite rma tests into Intel CI for tcp provider.

2023-10-20 22:43 UTC, shefty requested changes
The patches aren't clean when viewed individually.  The first patch removes several blank lines and adds printf calls.  The second path adds several blank lines, and removes the printfs.  The blank lines and printfs shouldn't be part of the first patch, so it stands alone better for cherry picking.  The second patch then wouldn't need to cleanup after the first patch.

2023-10-23 18:22 UTC, nikhilnanal commented
> The patches aren't clean when viewed individually. The first patch removes several blank lines and adds printf calls. The second path adds several blank lines, and removes the printfs. The blank lines and printfs shouldn't be part of the first patch, so it stands alone better for cherry picking. The second patch then wouldn't need to cleanup after the first patch.

2023-10-23 18:24 UTC, nikhilnanal commented
I have corrected the commits and then clicked on close by mistake, reopened again. Passes on the Jenkins CI.

2023-10-25 20:36 UTC, j-xiong commented on prov/tcp/src/xnet.h
> +	return (ep->util_ep.tx_msg_flags | flags) & FI_COMPLETION;
`tx_msg_flags` and `tx_op_flags` are the same w.r.t. `FI_COMPLETION`. There is no behavior difference before and after this patch.  The `*_msg_flags` fields are used as a way to pass optional `FI_COMPLETION` to other util calls (such as in `util_srx_recvmsg()`). The `*_op_flags` should be sufficient to cover all the scenarios that the default flags are checked.

2023-10-26 15:50 UTC, j-xiong commented on prov/tcp/src/xnet.h
> +	return (ep->util_ep.tx_msg_flags | flags) & FI_COMPLETION;
@shefty You are right. When enabling completion by default while using selective completions, the msg flags won't have FI_COMPLETION on.

2023-10-26 15:51 UTC, j-xiong approved these changes

2023-10-26 15:52 UTC, merged