Intel/CI: Fix missing test names in summary
ofiwg/libfabric pull request #9795
Opened 2024-02-07 20:08 UTC by Juee14Desai

OneCCL and OneCCL GPU stages were missing test names and correct
test numbers

SHMEM is missing PRK and ISx test names from the summary.
This patch adds the capability to find the test names and add
them to the passed and failed test lists for verbose reporting.
Tests will have the type of SHMEM test added as a prefix to them.

2024-02-07 20:39 UTC, zachdworkin requested changes
Can you fix my typo and fix the missing letters in the commit message for shmem? The U is missing from UH the P from PRK and the I from ISx

2024-02-07 20:39 UTC, zachdworkin commented on contrib/intel/jenkins/summary.py
> +        self.previouse = line
This has a typo previouse -> previous

2024-02-07 21:00 UTC, Juee14Desai commented on contrib/intel/jenkins/summary.py
> +        self.previouse = line
Done.

2024-02-07 23:48 UTC, zachdworkin approved these changes
I think the summary stage looks good. Can you also take a look at the summary stage before merging please?

2024-02-08 00:21 UTC, j-xiong commented
Please fix the indentation in the commit message for the second commit (shmem summary).

2024-02-08 04:52 UTC, Juee14Desai commented
Indentation has been fixed in recent commit.

2024-02-08 16:50 UTC, merged