prov/efa: Map EFA errnos to Libfabric codes
ofiwg/libfabric pull request #9974
Opened 2024-04-03 00:29 UTC by darrylabbate

This adds a rudimentary function to map proprietary EFA status codes to common Libfabric status codes. This is useful when reporting errors to the application for operations that rely solely on ibverbs or RDMA Core, such as CQ polling.

2024-04-03 00:29 UTC, darrylabbate commented on prov/efa/src/efa_errno.h
> +		return FI_EOTHER;
RFC

2024-04-03 00:31 UTC, darrylabbate commented on prov/efa/src/rdm/efa_rdm_pke_cmd.c
> +	int err = to_fi_errno(prov_errno);
Alternatively (or as a future improvement), `err` can be overridden based on some of the conditions below.

2024-04-03 18:13 UTC, shijin-aws requested changes

2024-04-03 18:13 UTC, shijin-aws commented on prov/efa/src/efa_errno.h
> +	case FI_EFA_ERR_ESTABLISHED_RECV_UNRESP:
`FI_EFA_ERR_ESTABLISHED_RECV_UNRESP` should be ECONNABOUTED

2024-04-03 18:13 UTC, shijin-aws commented on prov/efa/src/efa_errno.h
> +	case EFA_IO_COMP_STATUS_LOCAL_ERROR_QP_INTERNAL_ERROR:
The local invalid error seems more close to `FI_EINVAL`

2024-04-03 18:13 UTC, shijin-aws commented on prov/efa/src/efa_errno.h
> +	case EFA_IO_COMP_STATUS_LOCAL_ERROR_UNRESP_REMOTE:
This unresponsive remote (no handshake made) should be `EHOSTUNREACH`

2024-04-03 18:13 UTC, shijin-aws commented on prov/efa/src/efa_errno.h
> +		return FI_EOPNOTSUPP;
This should be EINVAL as well

2024-04-03 22:15 UTC, shijin-aws approved these changes

2024-04-04 02:42 UTC, shijin-aws commented
It seems windows build failed because the errno is not available

2024-04-05 23:58 UTC, darrylabbate commented
Need to re-run against new CI since old CI logs are gone

2024-04-05 23:58 UTC, darrylabbate commented
bot:aws:new:retest

2024-04-05 23:59 UTC, darrylabbate commented
bot:aws:retest

2024-04-06 00:02 UTC, a-szegel commented
bot:aws:retest

2024-04-08 19:11 UTC, darrylabbate commented
Windows error from AWS CI:
```
         C:\9974_1712364969\libfabric\prov\efa\src\efa_errno.h(170,22): error C2065: 'EREMOTEIO': undeclared identifier [C:\9974_1712364969\libfabric\libfabric.vcxproj]
         C:\9974_1712364969\libfabric\prov\efa\src\efa_errno.h(150,22): error C2065: 'EHOSTDOWN': undeclared identifier [C:\9974_1712364969\libfabric\libfabric.vcxproj]
```

2024-04-15 19:45 UTC, darrylabbate commented
The issue here is that `EREMOTEIO` and `EHOSTDOWN` (among others) are implementation-defined; the `fi_errno` codes aren't fully portable. This has gone unnoticed since many of the `fi_errno` codes are completely unused.

2024-04-17 17:23 UTC, shijin-aws commented
@j-xiong is  https://github.com/ofiwg/libfabric/pull/9974/commits/6d6f4bed2b9acab020c49e70959a2a332efb0e3c good to you?

2024-04-17 17:26 UTC, j-xiong approved these changes

2024-04-17 17:32 UTC, merged